dist: trusty

sudo: false
language: node_js
node_js:
  - 8
cache:
  bundler: true
  pip: true
  directories:
    - "$HOME/.npm"
    - "$HOME/.cache"
install:
- travis_retry gem install s3_website -v 3.4.0
- travis_retry npm ci
# the next command is to fix "SSLContext object is not available" error in awscli install
- travis_retry pyenv global 3.6
- travis_retry pip install awscli --upgrade --user
script:
- npm run build
- npm run test
after_script:
- ./s3_deploy.sh
