name: Continuous Integration

on: push

jobs:
  s3-deploy:
    name: S3 Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install Dependencies
        run: npm ci
      - uses: concord-consortium/s3-deploy-action@main
        with:
          bucket: models-resources
          prefix: sagemodeler
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # Parameters to GHActions have to be strings, so a regular yaml array cannot
          # be used. Instead the `|` turns the following lines into a string
          topBranches: |
            ["master"]
