name: Continuous Integration

on: push

jobs:
  s3-deploy:
    name: S3 Deploy
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '8'
      - name: Setup Ruby 2.4
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.4'
      - name: Set up Python (for aws cli)
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'
      - name: Install Dependencies
        run: |
          gem install s3_website -v 3.4.0
          pip install awscli --upgrade --user
          npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: ./s3_deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
